import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    const val exposed_core: String = "org.jetbrains.exposed:exposed-core:" +
            Versions.org_jetbrains_exposed

    const val exposed_java_time: String = "org.jetbrains.exposed:exposed-java-time:" +
            Versions.org_jetbrains_exposed

    const val exposed_jdbc: String = "org.jetbrains.exposed:exposed-jdbc:" +
            Versions.org_jetbrains_exposed

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://junit.org/junit5/
     */
    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:" +
            Versions.org_junit_jupiter

    /**
     * https://junit.org/junit5/
     */
    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:" +
            Versions.org_junit_jupiter

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_auth: String = "io.ktor:ktor-auth:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_gson: String = "io.ktor:ktor-gson:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_server_core: String = "io.ktor:ktor-server-core:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_server_netty: String = "io.ktor:ktor-server-netty:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_server_sessions: String = "io.ktor:ktor-server-sessions:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_server_test_host: String = "io.ktor:ktor-server-test-host:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_server_tests: String = "io.ktor:ktor-server-tests:" + Versions.io_ktor

    const val com_github_johnrengelman_shadow_gradle_plugin: String =
            "com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:" +
            Versions.com_github_johnrengelman_shadow_gradle_plugin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    /**
     * https://mariadb.com/kb/en/mariadb/about-mariadb-connector-j/
     */
    const val mariadb_java_client: String = "org.mariadb.jdbc:mariadb-java-client:" +
            Versions.mariadb_java_client

    /**
     * http://logback.qos.ch
     */
    const val logback_classic: String = "ch.qos.logback:logback-classic:" + Versions.logback_classic

    /**
     * https://github.com/phxql/argon2-jvm
     */
    const val argon2_jvm: String = "de.mkammerer:argon2-jvm:" + Versions.argon2_jvm

    /**
     * https://github.com/brettwooldridge/HikariCP
     */
    const val hikaricp: String = "com.zaxxer:HikariCP:" + Versions.hikaricp
}
