import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val logback_classic: String = "1.2.3"

  const val hikaricp: String = "3.3.1"

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2"

  const val argon2_jvm: String = "2.5"

  const val io_ktor: String = "1.2.3"

  const val exposed: String = "0.17.1" // available: "0.17.3"

  const val org_jetbrains_kotlin_jvm_gradle_plugin: String = "1.3.50"

  const val kotlin_scripting_compiler_embeddable: String = "1.3.50"

  const val kotlin_stdlib_jdk8: String = "1.3.41" // available: "1.3.50"

  const val org_junit_jupiter: String = "5.5.1"

  const val mariadb_java_client: String = "2.4.3"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "5.6.1"

  const val gradleCurrentVersion: String = "4.10.3"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
